# Nombre de la aplicación
spring.application.name=Test-Spring

# Conexión a MongoDB (local)
spring.data.mongodb.uri=mongodb://localhost:27017/Test

# Si quieres que Spring cree la base de datos si no existe
spring.data.mongodb.database=Test

# Opcional: mostrar logs de queries
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
